trigger:
  batch: true
  branches:
    include:
    - '*'

jobs:
- job: 'Test'
  strategy:
    matrix:
      Python36Windows:
        imageName: 'windows-2019'
        python.version: '3.6'
      Python37Mac:
        imageName: 'macos-latest'
        python.version: '3.7'
      Python38Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.8'
      Python39Windows:
        imageName: 'windows-latest'
        python.version: '3.9'
      Python310Mac:
        imageName: 'macos-latest'
        python.version: '3.10'
      Python311Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.11'
      Python311Windows:
        imageName: 'windows-latest'
        python.version: '3.11'
      Python311Mac:
        imageName: 'macos-latest'
        python.version: '3.11'
    maxParallel: 4
  pool:
    vmImage: $(imageName)

  steps:
  - checkout: self
    submodules: true

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python setup.py sdist
    displayName: 'Build sdist'

  - script: python -m mypy curated_transformers
    displayName: 'Run mypy'
    condition: ne(variables['python.version'], '3.6')

  - task: DeleteFiles@1
    inputs:
      contents: 'curated_transformers'
    displayName: 'Delete source directory'

  - script: |
      python -m pip freeze
      pip freeze --exclude pywin32 > installed.txt
      pip uninstall -y -r installed.txt
    displayName: 'Uninstall all packages'

  - bash: |
      SDIST=$(python -c "import os;print(os.listdir('./dist')[-1])" 2>&1)
      pip install dist/$SDIST
    displayName: 'Install from sdist'

  - script: |
      pip install -r requirements.txt
    displayName: 'Install test dependencies'

  - script: |
      python -m pytest --pyargs curated_transformers
    displayName: 'Run tests'
