model:
  type: autoencoder
  original_size: 300
  ratio: 2
  num_hidden: 1
  activation: sigmoid
  rezero: False
  normalize: True
loader:
  path: test.npy
  batch_size: 512
  normalizer: null
optimizer:
  learning_rate: 0.0001
  weight_decay: 0.0
scheduler:
  factor: 0.1
  patience: 2
loss:
  type: mse
  reduction: mean
training:
  epochs: 100
  patience: 5
