title: "Curated transformers XLM-R pipeline"

vars:
  lang: "nl"
  treebank: "UD_Dutch-Alpino"
  train_name: "nl_alpino-ud-train"
  dev_name: "nl_alpino-ud-dev"
  test_name: "nl_alpino-ud-test"
  # Quantization inevitably leads to a loss. If the loss is too large,
  # this leads to a model with an unacceptably low accuracy. This option
  # allows you to skip quantization of layers where the quantization
  # leads to a larger mean squared error than specified through this
  # option. The ideal value must be tuned per dataset and the acceptable
  # loss of accuracy.
  max_mse_qloss: 3e-6
  gpu: 0
  # Can either be 'layer-weighting' or 'no-layer-weighting'. The former
  # only uses the outputs of the last transformer layer in downstream
  # components, while the latter will learn task-specific, weighted
  # representations of all transformer layers for downstream usage.
  config_name: "no-layer-weighting"

directories: ["configs", "assets", "corpus", "training"]

assets:
  - dest: "assets/${vars.treebank}"
    git:
      repo: "https://github.com/UniversalDependencies/${vars.treebank}"
      branch: "master"
      path: ""

workflows:
  all:
    - preprocess
    - create-config
    - train
    - quantize
    - evaluate

commands:
  - name: "preprocess"
    help: "Convert data to spaCy format"
    script:
      - "mkdir -p corpus/${vars.treebank}"
      - "python -m spacy convert assets/${vars.treebank}/${vars.train_name}.conllu corpus/${vars.treebank}/ --n-sents 10 --merge-subtokens"
      - "mv corpus/${vars.treebank}/${vars.train_name}.spacy corpus/${vars.treebank}/train.spacy"
      - "python -m spacy convert assets/${vars.treebank}/${vars.dev_name}.conllu corpus/${vars.treebank}/ --n-sents 10 --merge-subtokens"
      - "mv corpus/${vars.treebank}/${vars.dev_name}.spacy corpus/${vars.treebank}/dev.spacy"
      - "python -m spacy convert assets/${vars.treebank}/${vars.test_name}.conllu corpus/${vars.treebank}/ --n-sents 10 --merge-subtokens"
      - "mv corpus/${vars.treebank}/${vars.test_name}.spacy corpus/${vars.treebank}/test.spacy"
    deps:
      - "assets/${vars.treebank}/${vars.train_name}.conllu"
      - "assets/${vars.treebank}/${vars.dev_name}.conllu"
      - "assets/${vars.treebank}/${vars.test_name}.conllu"
    outputs:
      - "corpus/${vars.treebank}/train.spacy"
      - "corpus/${vars.treebank}/dev.spacy"
      - "corpus/${vars.treebank}/test.spacy"

  - name: "create-config"
    help: "Create a config"
    script:
      - "mkdir -p configs/${vars.treebank}"
      - "cp configs/${vars.config_name}.cfg configs/${vars.treebank}/config.cfg"

  - name: "train"
    help: "Train the pipeline"
    script:
      - "python -m spacy train configs/${vars.treebank}/config.cfg --output training/${vars.treebank} --gpu-id ${vars.gpu} --nlp.lang=${vars.lang} --paths.train corpus/${vars.treebank}/train.spacy --paths.dev corpus/${vars.treebank}/dev.spacy"
    deps:
      - "configs/${vars.treebank}/config.cfg"
      - "corpus/${vars.treebank}/train.spacy"
      - "corpus/${vars.treebank}/dev.spacy"
    outputs:
      - "training/${vars.treebank}/model-best"

  - name: "quantize"
    help: "Quantize the pipeline"
    script:
      - "python -m spacy quantize-transformer --max-mse-loss ${vars.max_mse_qloss} training/${vars.treebank}/model-best training/${vars.treebank}/model-best-quantized"
    deps:
      - "training/${vars.treebank}/model-best"
    outputs:
      - "training/${vars.treebank}/model-best-quantized"

  - name: "evaluate"
    help: "Evaluate the pipeline on the test corpus."
    script:
      - "python -m spacy evaluate --gpu-id ${vars.gpu} training/${vars.treebank}/model-best corpus/${vars.treebank}/test.spacy"
      - "python -m spacy evaluate training/${vars.treebank}/model-best-quantized corpus/${vars.treebank}/test.spacy"
    deps:
      - "training/${vars.treebank}/model-best"
      - "training/${vars.treebank}/model-best-quantized"
      - "corpus/${vars.treebank}/test.spacy"

  - name: "evaluate-dev"
    help: "Evaluate the pipeline on the dev corpus."
    script:
      - "python -m spacy evaluate --gpu-id ${vars.gpu} training/${vars.treebank}/model-best corpus/${vars.treebank}/dev.spacy"
      - "python -m spacy evaluate training/${vars.treebank}/model-best-quantized corpus/${vars.treebank}/dev.spacy"
    deps:
      - "training/${vars.treebank}/model-best"
      - "training/${vars.treebank}/model-best-quantized"
      - "corpus/${vars.treebank}/dev.spacy"
